version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mongodb
    environment:
      DB_CONNECTION: mongodb
      DB_HOST: data-ood.tradesoft.ru
      DB_PORT: 27017
      DB_DATABASE: your_database_name
      DB_USERNAME: oodadmin
      DB_PASSWORD: IuV7pbVwna2Wt2k

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: your_database_name
      MONGO_INITDB_ROOT_USERNAME: oodadmin
      MONGO_INITDB_ROOT_PASSWORD: IuV7pbVwna2Wt2k





# Используем образ PHP
FROM php:8.1-fpm

# Установка необходимых пакетов и расширений
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip

# Установка расширения для поддержки MongoDB
RUN pecl install mongodb && docker-php-ext-enable mongodb

# Установка Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Устанавливаем рабочую директорию
WORKDIR /var/www/html

# Копируем зависимости проекта и устанавливаем их
COPY . .

# Устанавливаем зависимости через Composer
RUN composer install

# Команда для запуска веб-сервера Laravel
CMD php artisan serve --host=0.0.0.0 --port=8000
