version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mongodb
    environment:
      DB_CONNECTION: mongodb
      DB_HOST: data-ood.tradesoft.ru
      DB_PORT: 27017
      DB_DATABASE: your_database_name
      DB_USERNAME: oodadmin
      DB_PASSWORD: IuV7pbVwna2Wt2k

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: your_database_name
      MONGO_INITDB_ROOT_USERNAME: oodadmin
      MONGO_INITDB_ROOT_PASSWORD: IuV7pbVwna2Wt2k
